import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { getVersion } from "@tauri-apps/api/app";
import { listen } from "@tauri-apps/api/event";
import "./App.css";

type Lang="en"|"id";
type Quota={id:string;label:string;used:number|null;total:number|null;remaining_percent:number|null;reset_at:string|null;unlimited:boolean;is_credit_balance:boolean;currency:string|null};
type Account={connection_id:string;provider_id:string;provider_name:string;account_name:string;active:boolean;plan:string|null;quotas:Quota[];message:string|null;error:string|null};
type Data={server_online:boolean;authenticated:boolean;fetched_at:string;accounts:Account[];summary:{requests:number|null;tokens:number|null;cost:number|null}|null;error:string|null};
type Settings={server_url:string;refresh_interval_seconds:number;enable_notifications:boolean;open_on_startup:boolean;language:Lang;credit_budgets:Record<string,number>;hide_inactive:boolean;remember_password:boolean;quota_thresholds:number[];credit_threshold:number;provider_sort:string};
const defaults:Settings={server_url:"http://localhost:20128",refresh_interval_seconds:300,enable_notifications:true,open_on_startup:false,language:"en",credit_budgets:{},hide_inactive:false,remember_password:true,quota_thresholds:[20,5],credit_threshold:.5,provider_sort:"dashboard"};
const text={en:{soon:"soon",available:"quotas available",unavailable:"N/A",used:"remaining",reset:"resets in",connectTitle:"Connect monitor",connectHelp:"Enter your 9Router dashboard address and password.",dashboardPassword:"Dashboard password",connecting:"Connecting…",connect:"Connect",passwordNote:"The password is only used to create a session and is not stored.",settings:"Settings",language:"Language",refresh:"Refresh interval",minute:"minute",minutes:"minutes",notifications:"Quota notifications",hideInactive:"Hide inactive",remember:"Remember password securely",thresholds:"Notify below (%)",creditThreshold:"Credit alert below",sort:"Sort providers",noActive:"No active providers.",showInactive:"Show inactive",refreshing:"Refreshing…",refreshFailed:"Refresh failed",about:"About",openDashboard:"Open dashboard",startup:"Open on startup",save:"Save",disconnect:"Disconnect",connected:"Server connected",offline:"Server offline",empty:"No provider connections yet.",requests:"requests",tokens:"tokens",cost:"7-day cost",updated:"Updated",setBudget:"Set budget",editBudget:"Edit budget",budgetPrompt:"Enter your budget",budgetInvalid:"Budget must be greater than 0"},id:{soon:"segera",available:"quota tersedia",unavailable:"N/A",used:"tersisa",reset:"reset dalam",connectTitle:"Hubungkan monitor",connectHelp:"Masukkan alamat dashboard 9Router dan password-nya.",dashboardPassword:"Password dashboard",connecting:"Menghubungkan…",connect:"Hubungkan",passwordNote:"Password hanya digunakan untuk membuat sesi dan tidak disimpan.",settings:"Pengaturan",language:"Bahasa",refresh:"Interval refresh",minute:"menit",minutes:"menit",notifications:"Notifikasi quota",hideInactive:"Sembunyikan yang nonaktif",remember:"Ingat password dengan aman",thresholds:"Notifikasi di bawah (%)",creditThreshold:"Peringatan credit di bawah",sort:"Urutkan provider",noActive:"Tidak ada provider aktif.",showInactive:"Tampilkan nonaktif",refreshing:"Memperbarui…",refreshFailed:"Refresh gagal",about:"Tentang",openDashboard:"Buka dashboard",startup:"Buka saat startup",save:"Simpan",disconnect:"Putuskan koneksi",connected:"Server terhubung",offline:"Server offline",empty:"Belum ada provider connection.",requests:"request",tokens:"token",cost:"biaya 7 hari",updated:"Diperbarui",setBudget:"Atur budget",editBudget:"Ubah budget",budgetPrompt:"Masukkan budget Anda",budgetInvalid:"Budget harus lebih besar dari 0"}} as const;
function tr(lang:Lang){return text[lang];}
function resetIn(value:string|null,lang:Lang){if(!value)return"";const ms=new Date(value).getTime()-Date.now();if(ms<=0)return tr(lang).soon;const d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000);return lang==="en"?(d?`${d}d ${h}h`:h?`${h}h ${m}m`:`${m}m`):(d?`${d}h ${h}j`:h?`${h}j ${m}m`:`${m}m`);}
function remainingPercent(q:Quota){if(q.remaining_percent!=null)return Math.max(0,Math.min(100,q.remaining_percent));if(q.used!=null&&q.total)return Math.max(0,Math.min(100,(q.total-q.used)/q.total*100));return null;}
function color(p:number){return p<=15?"#f44336":p<=40?"#ff9800":"#4caf50";}
function credit(q:Quota,lang:Lang){if(q.total==null)return"N/A";const currency=(q.currency||"USD").toUpperCase();return `${new Intl.NumberFormat(lang==="en"?"en-US":"id-ID",{minimumFractionDigits:2,maximumFractionDigits:6}).format(q.total)} ${currency}`;}

function AccountCard({a,loading,lang,budgets,onBudget}:{a:Account;loading:boolean;lang:Lang;budgets:Record<string,number>;onBudget:(key:string,value:number)=>void}){
  const t=tr(lang);
  return <div className="provider-card">
    <div className="card-header"><div><span className="provider-name">{a.provider_name}</span>{a.account_name!==a.provider_name&&<span className="account-name">{a.account_name}</span>}</div>{loading?<span className="spinner"/>:<span className={`status-dot ${a.active&&!a.error?"active":"inactive"}`}/>}</div>
    <div className="card-status">{a.error||a.message||a.plan||`${a.quotas.length} ${t.available}`}</div>
    {a.active&&a.quotas.map(q=>{
      const key=`${a.connection_id}:${q.id}`;
      const budget=budgets[key];
      const p=q.is_credit_balance&&budget&&q.total!=null?Math.max(0,Math.min(100,q.total/budget*100)):remainingPercent(q);
      return <div className={`progress-container ${q.is_credit_balance?"credit-quota":""}`} key={q.id}>
        <div className="progress-label-row"><span>{q.label}</span>{q.is_credit_balance?<span className="credit-value">Credit: {credit(q,lang)}{budget&&` · ${Math.round(p||0)}% · ${(q.currency||"USD").toUpperCase()==="USD"?"$":(q.currency||"").toUpperCase()+" "}${budget.toLocaleString(lang==="en"?"en-US":"id-ID",{maximumFractionDigits:6})}`}</span>:<span style={{color:p==null?"#888":color(p)}}>{q.unlimited?"Unlimited":p==null?t.unavailable:`${Math.round(p)}% ${t.used}`}{q.reset_at&&` · ${t.reset} ${resetIn(q.reset_at,lang)}`}</span>}</div>
        {q.is_credit_balance&&<BudgetEditor budget={budget} currency={(q.currency||"USD").toUpperCase()} lang={lang} onSave={value=>onBudget(key,value)}/>}
        {(!q.is_credit_balance||budget)&&<div className="progress-track"><div className="progress-fill" style={{width:`${Math.max(0,Math.min(100,p||0))}%`,background:p==null?"#555":color(p)}}/></div>}
      </div>
    })}
  </div>
}
function BudgetEditor({budget,currency,lang,onSave}:{budget:number|undefined;currency:string;lang:Lang;onSave:(value:number)=>void}){
  const t=tr(lang);const[value,setValue]=useState(budget?.toString()||"");const[error,setError]=useState(false);const[editing,setEditing]=useState(!budget);
  useEffect(()=>{setValue(budget?.toString()||"");if(budget)setEditing(false)},[budget]);
  function submit(){const parsed=Number(value.replace(",","."));if(!Number.isFinite(parsed)||parsed<=0){setError(true);return;}setError(false);onSave(parsed);setEditing(false)}
  if(!editing)return <button className="budget-overlay" aria-label={t.editBudget} title={t.editBudget} onClick={e=>{e.stopPropagation();setEditing(true)}}/>;
  return <div className="budget-editor"><span>{t.setBudget}</span><div className={`budget-input ${error?"invalid":""}`}><span>{currency==="USD"?"$":currency}</span><input autoFocus inputMode="decimal" value={value} placeholder="2.00" onChange={e=>{setValue(e.target.value);setError(false)}} onKeyDown={e=>{e.stopPropagation();if(e.key==="Enter")submit();if(e.key==="Escape"&&budget)setEditing(false)}} onClick={e=>e.stopPropagation()}/><button onClick={e=>{e.stopPropagation();submit()}}>{t.save}</button></div>{error&&<small>{t.budgetInvalid}</small>}</div>
}
function Connection({settings,onConnected}:{settings:Settings;onConnected:(d:Data)=>void}){const t=tr(settings.language);const[url,setUrl]=useState(settings.server_url);const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function connect(){setBusy(true);setError("");try{onConnected(await invoke<Data>("router_login",{serverUrl:url,password}));}catch(e){setError(String(e));}finally{setBusy(false)}}return <div className="connection"><div className="brand">9Router</div><h2>{t.connectTitle}</h2><p>{t.connectHelp}</p><label>Server URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://9router.example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&connect()} placeholder={t.dashboardPassword}/></label>{error&&<div className="error-box">{error}</div>}<button className="primary" disabled={busy||!url||!password} onClick={connect}>{busy?t.connecting:t.connect}</button><small>{t.passwordNote}</small></div>}
function SettingsModal({value,onClose,onSave,onLogout}:{value:Settings;onClose:()=>void;onSave:(s:Settings)=>void;onLogout:()=>void}){
  const[s,setS]=useState(value);const[tab,setTab]=useState<"general"|"options">("general");const t=tr(s.language);
  return <div className="modal-overlay" onClick={onClose}><div className="modal-card" onClick={e=>e.stopPropagation()}>
    <button className="modal-close" onClick={onClose}>✕</button><div className="modal-title">{t.settings}</div>
    <div className="settings-tabs"><button className={tab==="general"?"active":""} onClick={()=>setTab("general")}>{s.language==="id"?"Umum":"General"}</button><button className={tab==="options"?"active":""} onClick={()=>setTab("options")}>{s.language==="id"?"Opsi":"Options"}</button></div>
    <div className="settings-tab-content">
      {tab==="general"?<>
        <label>{t.language}<select value={s.language} onChange={e=>setS({...s,language:e.target.value as Lang})}><option value="en">English</option><option value="id">Indonesia</option></select></label>
        <label>Server URL<input value={s.server_url} onChange={e=>setS({...s,server_url:e.target.value})}/></label>
        <label>{t.refresh}<select value={s.refresh_interval_seconds} onChange={e=>setS({...s,refresh_interval_seconds:Number(e.target.value)})}><option value={60}>1 {t.minute}</option><option value={300}>5 {t.minutes}</option><option value={600}>10 {t.minutes}</option><option value={1800}>30 {t.minutes}</option></select></label>
      </>:<div className="settings-checks">
        <label className="option-select">{t.sort}<select value={s.provider_sort} onChange={e=>setS({...s,provider_sort:e.target.value})}><option value="dashboard">Dashboard</option><option value="active">Active first</option><option value="lowest">Lowest quota</option><option value="name">Name</option></select></label>
        <label className="check"><input type="checkbox" checked={s.enable_notifications} onChange={e=>setS({...s,enable_notifications:e.target.checked})}/> {t.notifications}</label>
        <label className="check"><input type="checkbox" checked={s.hide_inactive} onChange={e=>setS({...s,hide_inactive:e.target.checked})}/> {t.hideInactive}</label>
        <label className="check"><input type="checkbox" checked={s.remember_password} onChange={e=>setS({...s,remember_password:e.target.checked})}/> {t.remember}</label>
        <label className="check"><input type="checkbox" checked={s.open_on_startup} onChange={e=>setS({...s,open_on_startup:e.target.checked})}/> {t.startup}</label>
      </div>}
    </div>
    <div className="settings-actions"><button className="primary" onClick={()=>onSave(s)}>{t.save}</button><button className="modal-btn-link" onClick={()=>invoke("open_url",{url:s.server_url})}>{t.openDashboard}</button><button className="danger" onClick={onLogout}>{t.disconnect}</button></div>
  </div></div>
}

export default function App(){const popupRef=useRef<HTMLDivElement>(null);const[data,setData]=useState<Data|null>(null);const[settings,setSettings]=useState(defaults);const[refreshing,setRefreshing]=useState(false);const[refreshError,setRefreshError]=useState(false);const[modal,setModal]=useState(false);const[pinned,setPinned]=useState(false);const[version,setVersion]=useState("…");const[,setTick]=useState(0);const lang=settings.language||"en";const t=tr(lang);
useEffect(()=>{getVersion().then(setVersion);invoke<Settings>("get_settings").then(s=>setSettings({...s,language:s.language||"en",credit_budgets:s.credit_budgets||{},hide_inactive:s.hide_inactive??false,remember_password:s.remember_password??true,quota_thresholds:s.quota_thresholds||[20,5],credit_threshold:s.credit_threshold??.5,provider_sort:s.provider_sort||"dashboard"}));invoke<Data>("get_router_data").then(setData);const timer=setInterval(()=>setTick(x=>x+1),60000);let off:(()=>void)|undefined;listen<Data>("router-updated",e=>setData(e.payload)).then(v=>off=v);return()=>{clearInterval(timer);off?.()};},[]);
useLayoutEffect(()=>{const popup=popupRef.current;if(!popup)return;let timer:number|undefined;const resize=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>invoke("set_window_height",{height:Math.ceil(popup.scrollHeight)}).catch(()=>{}),20)};const observer=new ResizeObserver(resize);observer.observe(popup);resize();return()=>{observer.disconnect();window.clearTimeout(timer)}},[]);
async function refresh(){if(refreshing)return;setRefreshing(true);setRefreshError(false);try{setData(await invoke<Data>("refresh_router",{force:true}));}catch{setRefreshError(true)}finally{setRefreshing(false)}}
async function save(s:Settings){await invoke("save_settings",{settings:s});setSettings(s);setModal(false);if(s.server_url!==settings.server_url){await invoke("router_logout");setData(null);}}
async function logout(){await invoke("router_logout");setData(null);setModal(false)}
async function setBudget(key:string,value:number){const next={...settings,credit_budgets:{...settings.credit_budgets,[key]:value}};await invoke("save_settings",{settings:next});setSettings(next)}
const logged=data?.authenticated;const visibleAccounts=(data?.accounts||[]).filter(a=>!settings.hide_inactive||a.active).sort((a,b)=>settings.provider_sort==="active"?Number(b.active)-Number(a.active):settings.provider_sort==="name"?a.provider_name.localeCompare(b.provider_name):settings.provider_sort==="lowest"?Math.min(...a.quotas.map(q=>remainingPercent(q)??101),101)-Math.min(...b.quotas.map(q=>remainingPercent(q)??101),101):0);return <div className="popup" ref={popupRef}><header className="popup-header"><span>9Router Usage</span><div className="header-actions"><button className={`btn-icon pin-button ${pinned?"pinned":""}`} onClick={()=>invoke<boolean>("toggle_pin").then(setPinned)} title={pinned?"Unpin window":"Keep window open"} aria-label={pinned?"Unpin window":"Keep window open"}><svg width="14" height="14" viewBox="0 0 24 24" fill={pinned?"currentColor":"none"} stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 17v5"/><path d="M5 17h14"/><path d="M6 17v-2.2a2 2 0 0 1 1.1-1.8L9 12V5H7V2h10v3h-2v7l1.9 1a2 2 0 0 1 1.1 1.8V17"/></svg></button><button className="btn-icon" title={t.settings} aria-label={t.settings} onClick={()=>setModal(true)}>⚙</button><button className="btn-icon" title="Refresh now" aria-label="Refresh now" onClick={refresh} disabled={!logged}>↻</button><button className="btn-close" title="Hide to tray" aria-label="Hide to tray" onClick={()=>invoke("hide_window")}>✕</button></div></header><main className="popup-body">{!logged?<Connection settings={settings} onConnected={setData}/>:<>{data.error&&<div className="error-box">{data.error}</div>}{visibleAccounts.length?visibleAccounts.map(a=><AccountCard key={a.connection_id} a={a} loading={refreshing} lang={lang} budgets={settings.credit_budgets} onBudget={setBudget}/>):<div className="empty">{settings.hide_inactive&&data.accounts.length?<>{t.noActive}<button className="inline-link" onClick={()=>setSettings({...settings,hide_inactive:false})}>{t.showInactive}</button></>:t.empty}</div>}</>}</main>{modal&&<SettingsModal value={settings} onClose={()=>setModal(false)} onSave={save} onLogout={logout}/>}<footer className="popup-footer"><span>9Router Usage v{version}</span>{refreshing?<span>{t.refreshing}</span>:refreshError?<button className="footer-retry" onClick={refresh}>{t.refreshFailed} · Retry</button>:data?.fetched_at&&<span>{t.updated} {new Date(data.fetched_at).toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"})}</span>}</footer></div>}
